---
abstract: 'Rate based sub dispatcher generator'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Rate
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.18
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/typester/Sub-Rate.git
version: 0.02
